export const USER_SEARCHED = "USER_SEARCHED";
export const MOVIE_REQUESTED = "MOVIE_REQUESTED";
export const RANDOM_MOVIE_RECEIVED = "RANDOM_MOVIE_RECEIVED";
export const MOVIE_RECEIVED = "MOVIE_RECEIVED";
export const MOVIE_FAILED = "MOVIE_FAILED";
export const DELETE_MOVIE = "DELETE MOVIE";